name: CI and Testing

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Specify the Node.js version you want

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run start  # Replace with your linting command

    - name: Run tests
      run: npm test  # Replace with your testing command
